org: nicolasramos41
app: aws-python-pdf-generator
service: aws-python-pdf-generator
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.8

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-python-requirements
